 CREATE TABLE "RX"."NPA_NXX_UNIT_DETAILS"
   (    "NPA_NXX_UNIT_AI" NUMBER,
    "NPA" VARCHAR2(4 BYTE),
    "NXX" VARCHAR2(4 BYTE),
    "UNIT_NUM" VARCHAR2(4 BYTE),
    "STATE_CD" VARCHAR2(4 BYTE),
    "COMPANY_NAME" VARCHAR2(20 BYTE),
    "IS_ACTIVE" VARCHAR2(1 BYTE),
    "CREATED_DATE" DATE,
    "LAST_MODIFIED_DATE" DATE,
     CONSTRAINT "NPA_NXX_UNIT_PK" PRIMARY KEY ("NPA", "NXX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "RX_DATA_01"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
  TABLESPACE "RX_INDX_01" ;



 CREATE INDEX "RX"."NPA_NXX_UNIT_IDX01" ON "RX"."NPA_NXX_UNIT_DETAILS" ("UNIT_NUM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "RX_INDX_01" ;



 CREATE INDEX "RX"."NPA_NXX_UNIT_IDX02" ON "RX"."NPA_NXX_UNIT_DETAILS" ("STATE_CD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "RX_INDX_01" ;